# Generated by Django 3.2.5 on 2022-04-17 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_student_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(1, 'پسر'), (2, 'دختر'), (3, 'نامشخص')], default=3, max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 11, 15, 20, 651502)),
        ),
    ]
