# Generated by Django 3.2.5 on 2022-04-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Friendship', '0001_initial'),
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.lesson'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='search_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Friendship.searchaccount'),
        ),
    ]
