# Generated by Django 3.2.5 on 2022-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='state',
            field=models.CharField(choices=[(1, 'درحال انجام'), (2, 'موفق شده'), (3, 'شکست خورده')], default=1, max_length=11),
        ),
    ]
