# Generated by Django 3.2.5 on 2022-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0002_curriculumitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumitem',
            name='day',
            field=models.CharField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دوشنبه'), (4, 'سه شنبه'), (5, 'چهارشنبه'), (6, 'پنجشنبه'), (7, 'جمعه')], max_length=8),
        ),
    ]
