# Generated by Django 3.2.5 on 2022-04-17 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lessons', '0004_auto_20220416_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'شنبه'), (2, 'یکشنبه'), (3, 'دوشنبه'), (4, 'سه شنبه'), (5, 'چهارشنبه'), (6, 'پنجشنبه'), (7, 'جمعه')], max_length=8)),
                ('week', models.IntegerField()),
                ('scheduleItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.scheduleitem')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
