# Generated by Django 3.2.5 on 2022-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[('عمومی', 1), ('اختصاصی', 2)], max_length=7)),
                ('icon', models.ImageField(upload_to='./lesson icons')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 1), ('یکشنبه', 2), ('دوشنبه', 3), ('سه شنبه', 4), ('چهارشنبه', 5), ('پنجشنبه', 6), ('جمعه', 7)], max_length=8)),
                ('time', models.IntegerField(default=0)),
                ('question', models.IntegerField(default=0)),
                ('detail', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
            ],
        ),
    ]
