# Generated by Django 3.2.5 on 2022-04-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleweek',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.lesson'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.scheduleweek'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.grade'),
        ),
    ]
