# Generated by Django 3.2.5 on 2022-04-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lessons', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.grade'),
        ),
    ]
