# Generated by Django 3.2.5 on 2022-04-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='day',
        ),
    ]
