# Generated by Django 3.2.5 on 2022-04-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0003_remove_scheduleitem_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='week',
        ),
        migrations.DeleteModel(
            name='ScheduleWeek',
        ),
    ]
